### ISSUE TITLE
Chat history items text issue

### ISSUE THREAD

**Issue by yagizhanNY** [yagizhanNY/openai-chatgpt3-clone#19]
![image](https://user-images.githubusercontent.com/41087670/236738566-de7e085e-639b-4841-93f5-907f65dd8e9e.png)

Text of history items are not visible.

**Comment by mehul1011** [comment]
Sure checking on this.

**Comment by mehul1011** [comment]
Hi, @yagizhanNY, hope you are doing great.
Have found the root cause, the initial logic is a bit messy, cleaning it up (basically data passing from chat to sidebar or from another way needs to be handled like the user could create a new chat first or just start typing), will be pushing the changes after validating.
